### ISSUE TITLE
Settings not loading from turbo.json

### ISSUE THREAD

**Issue by AvidRambo** [dalezak/turbo-ios-base#1]
Hey thanks for the awesome starting point for us who know nothing about Swift!

I'm not sure if this issue is related to my rails setup. I created a new project and followed the instructions from the readme.

![CleanShot 2021-06-25 at 18 10 01](https://user-images.githubusercontent.com/19627351/123489709-938fd680-d5e0-11eb-82df-f6980879310f.png)

![CleanShot 2021-06-25 at 18 13 26](https://user-images.githubusercontent.com/19627351/123489938-144ed280-d5e1-11eb-820e-4450ce1bcb71.png)

**Comment by dalezak** [comment]
Hmm, your `turbo.json` looks fine, try changing your `print` lines to
```
print("path \(path)")
print("text \(text)")
```
And also add `print("json \(json)")` inside the `if let json` block, that should output the contents.

**Comment by AvidRambo** [comment]
Weird, right?

![CleanShot 2021-06-25 at 19 37 05](https://user-images.githubusercontent.com/19627351/123494487-fd62ad00-d5ed-11eb-8fa6-aaa7af423790.png)

![CleanShot 2021-06-25 at 20 41 51](https://user-images.githubusercontent.com/19627351/123496368-cabcb280-d5f5-11eb-8d81-7d0017d45250.png)

This seems to be working. The request must be made from WK View for any reason?

```
    func loadSettings() -> Dictionary<String, AnyObject> {
        let path = turboPath("/turbo.json")
        let url = URL(string: path)
        let semaphore = DispatchSemaphore(value: 0)
        var text: String = ""
        
        let task = URLSession.shared.dataTask(with: url!) {(data, response, error) in
            text = String(data: data!, encoding: String.Encoding.utf8)!
            semaphore.signal()
        }
        task.resume()
        semaphore.wait()

        if let json = stringToDictionary(text: text) {
            return (json["settings"] as? Dictionary<String, AnyObject>)!
        }
        return [:]
    }
```

**Comment by dalezak** [comment]
Do you have `@hotwired/turbo-rails` in your `package.json`? 

I just realized I forgot this in the instructions.

If you are using Yarn, do `yarn add @hotwired/turbo-rails`.

If you are using NPM, do `npm add @hotwired/turbo-rails`.

https://www.npmjs.com/package/@hotwired/turbo-rails

**Comment by dalezak** [comment]
Oh yes, and one more thing, in your `Info.plist`, you need to add:

```
NSAppTransportSecurity -> NSAllowsLocalNetworking -> Yes
```

<img width="488" alt="Screen Shot 2021-06-25 at 7 49 10 PM" src="https://user-images.githubusercontent.com/91811/123498624-6b0ed900-d5ee-11eb-8bd0-6d87caf9a98e.png">

**Comment by dalezak** [comment]
@codigodo I updated the readme with instructions for [adding turbo package](https://github.com/dalezak/turbo-ios-base#add-turbo-javascript) and [transport security settings](https://github.com/dalezak/turbo-ios-base#update-infoplist-transport-security). Let me know if these two things fix your issue. 🤞

**Comment by dalezak** [comment]
Alright @codigodo, I tested out your changes and they seem to work well. 

So I've [updated loadSettings](https://github.com/dalezak/turbo-ios-base/blob/main/App/TurboController.swift#L166) to use `URLSession.shared.dataTask` instead. 

Can you pull the latest to verify the changes still work for you?

**Comment by AvidRambo** [comment]
Works great!

**Comment by dalezak** [comment]
Good news, closing issue.
