### ISSUE TITLE
App Crashes with Error on fetching env variable on TestFlight

### ISSUE THREAD

**Issue by notthatjen** [dalezak/turbo-ios-base#6]
So I was able to deploy my app to testflight, but when I tried testing the app it started crashing and the report points me to this code. Any easy fix, anything I'm missing here?

<img width="1065" alt="image" src="https://user-images.githubusercontent.com/26903002/181029450-4f97074b-dd86-4e7d-b9c7-c25cd7672565.png">

**Comment by joemasilotti** [comment]
Those variables are only set when running from Xcode. You will need to use a different mechanism we when deployed to the App Store and TestFlight.

**Comment by notthatjen** [comment]
> 

Gotcha! Thanks for clarifying.
